spring:
  application:
    name: test-cardpay
  main:
    web-environment: false
    banner-mode: "OFF"
cardplay:
  test:
    executors:
      executor-service-executor:
        core-pool-size: 10
        max-pool-size: 25
        queue-capacity: 30
        thread-name-prefix: "ExcecutorService-"
      file-task-executor:
        core-pool-size: 10
        max-pool-size: 25
        queue-capacity: 30
        thread-name-prefix: "FileReading-"
      json-parser-executor:
        core-pool-size: 10
        max-pool-size: 25
        queue-capacity: 30
        thread-name-prefix: "JsonParsing-"
      csv-parser-executor:
        core-pool-size: 10
        max-pool-size: 25
        queue-capacity: 30
        thread-name-prefix: "CsvParsing-"
logging:
  level:
    org:
      springframework: warn
      hibernate: warn